[package]
name = "batsat-c"
version = "0.1.0"
authors = ["Simon Cruanes"]

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]

#ocaml = "0.4"
batsat = {path = "../batsat/", features=[]}

[workspace]
